import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import "./App.scss";

import NavBar from "./components/NavBar";
import { ThemeProvider } from "./context/ThemeContext";
import Footer from "./components/Footer";
import BootstrapClient from "./components/BootstrapClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
        <div className="d-flex flex-column min-vh-100">
          <NavBar />
          <main className="flex-grow-1">
            {children}
          </main>
          <Footer />
        </div>
        </ThemeProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
