import "./globals.css";
import "./App.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex flex-column min-vh-100">
          {children}
        </div>
      </body>
    </html>
  );
}
